version: '3'

services:

  app:
    image: app
    container_name: app
    restart: "always"
    volumes:
      - /cpp_practice:/opt/app
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

